---
- name: Set ModPageSpeed configuration file
  template:
    src: mod-pagespeed.conf.j2
    dest: "{{ pagespeed_apache_conf_path }}"
    backup: True
  when: pagespeed_webserver == 'apache' and not pagespeed_cpanel
  notify: restart web service

- name: Set EA4 ModPageSpeed configuration file
  template:
    src: mod-pagespeed.conf.j2
    dest: "{{ pagespeed_apache_cpanel_conf_path }}"
    backup: True
  when: pagespeed_webserver == 'apache' and pagespeed_cpanel
  notify: restart web service

- name: Set NgxPageSpeed configuration file
  template:
    src: ngx-pagespeed.conf.j2
    dest: /etc/nginx/pagespeed.conf
    backup: True
  when: pagespeed_webserver == 'nginx'
  notify: restart web service
