---
- name: Include OS-specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- import_tasks: install-mod-pagespeed.yml
  when: pagespeed_webserver == "apache"

- import_tasks: install-ngx-pagespeed.yml
  when: pagespeed_webserver == "nginx"

- import_tasks: configure.yml
